name: XBanCheating
main: XBanCheating\Main
version: 4.2.0
api: 
- 1.0.0
- 1.12.0
- 2.0.0
- 2.1.0
- 3.0.0
- 3.0.0-ALPHA1
- 3.0.0-ALPHA2
load: POSTWORLD
author: SnowXxm

commands:
 xbc:
  description: "［XBanCheating］总命令"
  usage: "/xbc <admin | adminlist>"
  permission: XBanCheating.command.xbc
permissions:
 XBanCheating.command.xbc:
  default: op
  description: "［XBanCheating］反作弊插件指令"
