name: XBanCheating
main: XBanCheating\Main
version: 2.1.0
api: 2.0.0
load: POSTWORLD
author: SnowXxm,MattTradis

commands:
 xbc:
  description: "［XBanCheating］总命令"
  usage: "/xbc <admin | adminlist>"
  permission: XBanCheating.command.xbc
permissions:
 XBanCheating.command.xbc:
  default: op
  description: "［XBanCheating］反作弊插件指令"
